name: Load Test

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "The URL of the application to test"
        required: true
        default: "http://default-url"

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Gatling Docker Image
        run: docker pull europe-west3-docker.pkg.dev/your-project/gatling-images/gatling:latest

      # - name: Run Gatling Load Test
      #   env:
      #     BASE_URL: ${{ inputs.target_url }}
      #   run: |
      #     docker run --rm \
      #       -e BASE_URL=$BASE_URL \
      #       europe-west3-docker.pkg.dev/your-project/gatling-images/gatling:latest
      - name: Run Gatling Load Test
        env:
         BASE_URL: ${{ inputs.target_url }}
        run: |
          docker run --rm \
            -e BASE_URL=$BASE_URL \
            -v $GITHUB_WORKSPACE/simulations:/gatling/simulations \
            europe-west3-docker.pkg.dev/your-project/gatling-images/gatling:latest

