name: Gatling Workflow

on:
  push:
    branches:
      - main
  pull_request:

env:
  PROJECT_ID: 'sb-izal-20250103-132315'
  PROJECT_NO: '155209852551'
  GH_IDENTITY_POOL_ID: 'gh-identity-pool'

jobs:
  # Job: Gatling Load Test
  gatling:
    name: Run Load Tests with Gatling
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Step 1: Check out the Python app repository (with Gatling config)
      - name: Checkout Python App repository
        uses: actions/checkout@v3
        with:
          repository: StrikerASD/python-app-gatling
          ref: main

      # Step 2: Authenticate to GCP (for pulling Gatling Docker image)
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/${{env.PROJECT_NO}}/locations/global/workloadIdentityPools/${{env.GH_IDENTITY_POOL_ID}}/providers/gh-provider'
          service_account: 'gcp-github-access@${{env.PROJECT_ID}}.iam.gserviceaccount.com'

      # Step 3: Configure Docker to use Artifact Registry
      - name: Configure Docker
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      # Step 4: Pull and Run Gatling Docker Image
      - name: Run Gatling Load Test
        run: |
          docker run \
            -e BASE_URL=${{ secrets.BASE_URL }} \
            europe-west3-docker.pkg.dev/sb-izal-20250103-132315/gatling-tests/gatling:latest
          
